Adds spanish language mi propia senda logo
bloom-works/ownpath pull request #16
Opened 2022-07-28 19:17 UTC by jlhogan

2022-07-28 20:07 UTC, amdarnell7 approved these changes

2022-07-29 13:31 UTC, admoorgit requested changes
Two tweaks and we good:

- Change "by" to "por"
- Change font from Source Sans Pro to Trebuchet please

2022-08-04 14:40 UTC, admoorgit approved these changes
bee yoo tee full

2022-08-04 14:42 UTC, ElvisJG approved these changes

2022-08-04 16:35 UTC, merged