Incorporate LADDERS push 20221118-145437557
bloom-works/ownpath pull request #176
Opened 2022-11-18 14:54 UTC by cdhs-bha-data-services-sys

Updated LADDERS dataset

2022-11-21 17:00 UTC, admoorgit requested changes
Hey look at those badges!
Few things and we'll be good:
- Decrease padding in .jUXLAr from .5rem to .25rem (buttons are a tad tall currently)
- Telehealth options is missing it's tooltip text — is it not in the spreadsheet?
- Q: can screen readers access this tooltip content? does it need to be a click instead of a hover to make it readable?
- Compare isn't on this PR but yes badges should be in there

2022-11-22 15:24 UTC, jlhogan commented
@admoorgit reduced padding and added telehealth tooltip. I assume the tooltip is accessible, because we're leveraging a USWDS component from truss... the tooltip content is in the DOM always, even when not visible on the screen and has appropriate aria labelled-by values, so I think we're good!

2022-11-23 13:58 UTC, admoorgit approved these changes

2022-11-23 18:37 UTC, jlhogan approved these changes

2022-11-23 19:29 UTC, merged