created and styled Results Pagination component, added Google Analyti…
bloom-works/ownpath pull request #213
Opened 2022-12-06 20:14 UTC by SMakaiTakori

## Changes

Created and styled Results Pagination component for Results view. Added Google Analytics events to track clicks on pagination buttons.

## Screenshots

![Screenshot 2022-12-06 150728](https://user-images.githubusercontent.com/20325483/206012299-c4be6716-ffee-4ea5-ad67-e0256c0c6925.png)
![Screenshot 2022-12-06 150700](https://user-images.githubusercontent.com/20325483/206012300-5d382667-6357-4ab5-bfc2-02ca17d83061.png)
![Screenshot 2022-12-06 150824](https://user-images.githubusercontent.com/20325483/206012301-2a727bf6-54f2-4574-8bbd-aae2c932957f.png)

## Checklist

- ~[ ] if adds a new page, adds accessibility tests~
- ~[ ] if adds a new page or new interaction, adds e2e test~
- [x] if adds a new page or new interaction, sends google analytics events and updates [GA doc](https://docs.google.com/document/d/1DfQDUNZPO3B352EhUwXp0el6qrAWz8Jq9cTa1yv8Ty4/edit)
- ~[ ] if changes filter functionality, updates [filters doc]~(https://docs.google.com/document/d/1yEdo7IpHCtEKNNF6FMLapBUgcPw_8CY7wGwxKTdtJrU/edit)

Fixes [https://app.asana.com/0/1202105544020589/1202513876082735/f]

2022-12-06 22:03 UTC, jlhogan reviewed
LGTM! One blocker, one nit:
blocker: translated content! 
nit: renaming `Paging` to something more explicit (maybe `PaginationConfig`) for both the interface type and the context props.

2022-12-06 22:03 UTC, jlhogan commented on src/components/Pagination.tsx
> +  const { paging, setPaging } = useContext(PaginationContext);
can we rename these to something more explicit? `paginationConfig` ?

2022-12-09 15:25 UTC, SMakaiTakori commented on src/components/Search/ResultsList.tsx
> +          } of ${results.length}`}{" "}
Awesome, thank you for the example!

2022-12-12 18:54 UTC, admoorgit requested changes
Great work! Things are mostly working as expected with only a few things to tweak:
- Expected to be at the top of the page when changing pages but scroll level persists. Please pop us to the top of the page on click
- Hover state breaks the bottom of the box on Safari (screen attached) 
<img width="177" alt="image" src="https://user-images.githubusercontent.com/72033897/207129433-222ff0f9-75fa-470c-b412-e8fde6dd8454.png">
- # of pins vs. visible results issue — we either need to only show 20 pins at a time OR make it so when someone clicks a pin it jumps them to that page/result — but that may be disorienting? What're y'alls thoughts here? (for the record, originally I was picturing it only showing 1-20, then 21-30, etc. but that may not be the best approach)

2022-12-14 12:52 UTC, jlhogan commented
@admoorgit updated! Note that the resetting to top on next page will be handled by the telehealth filters PR fix for resetting to top on filter change, so you  won't see that in this branch until the other one has been merged.

2022-12-14 16:43 UTC, admoorgit commented
@SMakaiTakori One quick change and we're all good!
Let's center the page numbers on mobile. Everything looks great!

2022-12-14 21:23 UTC, SMakaiTakori commented
@admoorgit I went ahead and updated the styling for the pagination buttons to become centered on mobile view. We should be good to go after you give it one more look. Thanks!

2022-12-14 21:52 UTC, admoorgit commented
Centered and looking nice! I DID discover something new, however:

- The page numbers need to update as you page through them. As of now, if I go to page 3 on mobile, my choices are pages 1-3, then the last page only — and I have no way to get to other pages 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/72033897/207722535-38fe66f4-248e-4628-949c-dfaedf5556df.png">

- This is more of an issue because there is no next/prev on mobile. The functionality is partially outlined in the USWDS Figma. Basically if we don't have next/prev, we need to show the page before and after so people can go page by page.
<img width="246" alt="image" src="https://user-images.githubusercontent.com/72033897/207722218-9853ca5d-837b-4a7d-818b-dddd263d8495.png">

2022-12-15 21:35 UTC, SMakaiTakori commented
@admoorgit I went ahead and made the change to allow the `previous` and `next` buttons to appear on mobile. When you get a chance you can have a look. Here is a screenshot as well. Thanks!

![mobile_pagination](https://user-images.githubusercontent.com/20325483/207971915-34cf374b-a2c3-4faa-a379-e4286fa320c4.png)

2022-12-16 16:40 UTC, admoorgit commented
Looks good to me! Next/Prev on mobile work as expected. Knowing there.

2022-12-16 16:41 UTC, admoorgit approved these changes
Looks good to me!

2022-12-16 17:32 UTC, merged