Add branded page title
bloom-works/ownpath pull request #6
Opened 2022-07-25 20:34 UTC by jeffmaher

Noticed that the page title still said "Care Directory", so just added in something more in line with the brand. Does this work?

2022-07-25 21:21 UTC, amdarnell7 requested changes
@jeffmaher can we start with just OwnPath and Mi Propia Senda to simplify?

2022-07-26 11:08 UTC, jlhogan approved these changes

2022-07-26 12:04 UTC, amdarnell7 approved these changes

2022-07-26 12:13 UTC, admoorgit approved these changes

2022-07-26 12:15 UTC, merged