provider udpate info on detail page
bloom-works/ownpath pull request #74
Opened 2022-09-06 15:09 UTC by cathydeng

from this asana task: https://app.asana.com/0/1202105544020589/1202778144943641/f

<img width="655" alt="Screen Shot 2022-09-06 at 8 02 52 AM" src="https://user-images.githubusercontent.com/1406537/188669804-332f5cb2-8fb7-4d88-82cc-db98fc6d5414.png">

couple thoughts: 
- this looks kinda awk after implementing it b/c it's visually similar to the get directions button, so it overshadows the CTA
- it's now very visually prominent, when the relevant audience for this is small (providers with access to update, rather than general public)
- there are now so many diff pieces of info near the bottom of the screen - complaint, last updated time, provider update info, privacy info, faq - that it's getting kinda cluttered

should we de-emphasize this visually? e.g. a similar section to the complaint (tho not sure if that's confusing b/c it's totally diff content for diff audiences) or tuck away in a tooltip near the last updated info? should we make it more immediately clear that this is only relevant to providers and not ppl seeking care?

2022-09-06 16:56 UTC, jlhogan commented
I think my vote would be to match the complaint section: "Is this provider data incorrect?"  and then make it clear who the action is available to (providers) in the expanded content

2022-09-06 23:56 UTC, admoorgit requested changes
Since this is the most important CTA **for providers**, I'm fine with it being blue/obvious. At the very least, I'd like to stick with what the client approved and test it.  Let's move the "Data last updated" line to underneath the box, though, so it's not as awkward between the Complaint box and this one. Would also like to add more space above "Have a concern..." so it's less cluttered. Let's add 5rem above.

2022-09-07 17:19 UTC, cathydeng commented on src/components/ResultDetail/ProviderUpdateInfo.tsx
> +          <Link href={BHA_UPDATE_URL} className="dark-background">
used Trans here instead of react markdown so that i can use the existing styling for links on dark bg

2022-09-07 18:40 UTC, jlhogan approved these changes
👩‍⚕️

2022-09-07 18:40 UTC, jlhogan commented on src/index.css
> +.dark-background {
These can be one rule 
```
.dark-background, .usa-link.dark-background {
  color: white;
}
```

2022-09-07 19:08 UTC, admoorgit approved these changes
LGTM!

2022-09-07 23:33 UTC, merged